# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Downloads\img_filter_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure
import sys
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1209, 738)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_image_filtering = QtWidgets.QWidget()
        self.tab_image_filtering.setObjectName("tab_image_filtering")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_image_filtering)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Title_Spat = QtWidgets.QLabel(self.tab_image_filtering)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_Title_Spat.setFont(font)
        self.label_Title_Spat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title_Spat.setObjectName("label_Title_Spat")
        self.gridLayout_2.addWidget(self.label_Title_Spat, 0, 1, 1, 1)
        self.label_Title_Freq = QtWidgets.QLabel(self.tab_image_filtering)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_Title_Freq.setFont(font)
        self.label_Title_Freq.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title_Freq.setObjectName("label_Title_Freq")
        self.gridLayout_2.addWidget(self.label_Title_Freq, 0, 2, 1, 1)
        self.label_Title_Orig = QtWidgets.QLabel(self.tab_image_filtering)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.label_Title_Orig.setFont(font)
        self.label_Title_Orig.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Title_Orig.setObjectName("label_Title_Orig")
        self.gridLayout_2.addWidget(self.label_Title_Orig, 1, 0, 1, 1)
        self.label_Title_Fil = QtWidgets.QLabel(self.tab_image_filtering)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.label_Title_Fil.setFont(font)
        self.label_Title_Fil.setObjectName("label_Title_Fil")
        self.gridLayout_2.addWidget(self.label_Title_Fil, 2, 0, 1, 1)
        self.widget_Orig_Spat = QtWidgets.QWidget(self.tab_image_filtering)
        self.widget_Orig_Spat.setObjectName("widget_Orig_Spat")
        # self.gridLayout_2.addWidget(self.widget_Orig_Spat, 1, 1, 1, 1)
        self.widget_Orig_Freq = QtWidgets.QWidget(self.tab_image_filtering)
        self.widget_Orig_Freq.setObjectName("widget_Orig_Freq")
        # self.gridLayout_2.addWidget(self.widget_Orig_Freq, 1, 2, 1, 1)
        self.widget_Filt_Spat = QtWidgets.QWidget(self.tab_image_filtering)
        self.widget_Filt_Spat.setObjectName("widget_Filt_Spat")
        # self.gridLayout_2.addWidget(self.widget_Filt_Spat, 2, 1, 1, 1)
        self.widget_Filt_Freq = QtWidgets.QWidget(self.tab_image_filtering)
        self.widget_Filt_Freq.setObjectName("widget_Filt_Freq")
        # self.gridLayout_2.addWidget(self.widget_Filt_Freq, 2, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_2.setRowStretch(2, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comboBox_filters = QtWidgets.QComboBox(self.tab_image_filtering)
        self.comboBox_filters.setEditable(True)
        self.comboBox_filters.setObjectName("comboBox_filters")
        self.horizontalLayout.addWidget(self.comboBox_filters)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_image_filtering, "")
        self.tab_histogram = QtWidgets.QWidget()
        self.tab_histogram.setObjectName("tab_histogram")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_histogram)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_Hist_Title_Filt = QtWidgets.QLabel(self.tab_histogram)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.label_Hist_Title_Filt.setFont(font)
        self.label_Hist_Title_Filt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Hist_Title_Filt.setObjectName("label_Hist_Title_Filt")
        self.gridLayout_4.addWidget(self.label_Hist_Title_Filt, 0, 1, 1, 1)
        self.graphicsView_Orig = PlotWidget(self.tab_histogram)
        self.graphicsView_Orig.setObjectName("graphicsView_Orig")
        self.gridLayout_4.addWidget(self.graphicsView_Orig, 2, 0, 1, 1)
        self.label_Hist_Title_Orig = QtWidgets.QLabel(self.tab_histogram)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.label_Hist_Title_Orig.setFont(font)
        self.label_Hist_Title_Orig.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Hist_Title_Orig.setObjectName("label_Hist_Title_Orig")
        self.gridLayout_4.addWidget(self.label_Hist_Title_Orig, 0, 0, 1, 1)
        self.graphicsView_Filt = PlotWidget(self.tab_histogram)
        self.graphicsView_Filt.setObjectName("graphicsView_Filt")
        self.gridLayout_4.addWidget(self.graphicsView_Filt, 2, 1, 1, 1)

        self.widget_Orig_Hist = QtWidgets.QWidget(self.tab_histogram)
        self.widget_Orig_Hist.setObjectName("widget_Orig_Hist")
        # self.gridLayout_4.addWidget(self.widget_Orig_Hist, 1, 0, 1, 1)
        
        self.widget_Filt_Hist = QtWidgets.QWidget(self.tab_histogram)
        self.widget_Filt_Hist.setObjectName("widget_Filt_Hist")
        self.gridLayout_4.addWidget(self.widget_Filt_Hist, 1, 1, 1, 1)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_4.setRowStretch(2, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_histogram, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1209, 26))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImage = QtWidgets.QAction(MainWindow)
        self.actionImage.setObjectName("actionImage")
        self.menuOpen.addAction(self.actionImage)
        self.menubar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Title_Spat.setText(_translate("MainWindow", "Spatial Domain"))
        self.label_Title_Freq.setText(_translate("MainWindow", "Frequency Domain"))
        self.label_Title_Orig.setText(_translate("MainWindow", "Original"))
        self.label_Title_Fil.setText(_translate("MainWindow", "Filtered"))
        self.comboBox_filters.setCurrentText(_translate("MainWindow", "Choose a Filter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_image_filtering), _translate("MainWindow", "Image Filtering"))
        self.label_Hist_Title_Filt.setText(_translate("MainWindow", "Filtered"))
        self.label_Hist_Title_Orig.setText(_translate("MainWindow", "Original"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_histogram), _translate("MainWindow", "Histogram Equalization"))
        self.menuOpen.setTitle(_translate("MainWindow", "File"))
        self.actionImage.setText(_translate("MainWindow", "Open"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

